      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name drugtargets3dhuman

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/app-backend:${{ github.sha }} \
            -f app/Dockerfile app

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/app-backend:${{ github.sha }}
